"""The self-heal loop, closed end-to-end on a real shape.

produce (a drifted derived file) -> decide (governed to propose_pr) -> remediate (open a
reviewable fix PR carrying the regenerated bytes). No shared governance file is edited: the
new class is governed via an injected policy, proving the loop without touching the registry.
"""
import dataclasses
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from automation.beacon_producers import propose_derived_content_fix  # noqa: E402
from automation.policy import DEFAULT_POLICY  # noqa: E402
from automation.responder import decide  # noqa: E402
from automation.self_heal import remediate  # noqa: E402

# Govern the new class to `weak` -> propose_pr, via an injected policy (registry untouched).
POLICY = dataclasses.replace(
    DEFAULT_POLICY,
    law_by_kind={**DEFAULT_POLICY.law_by_kind, "derived_content_drift": "weak"},
)


def test_no_beacon_when_in_sync():
    assert propose_derived_content_fix(
        path="gen/x.txt", current="same", expected="same", repo="o/r"
    ) is None


def test_producer_carries_the_corrected_bytes():
    b = propose_derived_content_fix(
        path="gen/registry.json", current="OLD", expected="NEW", repo="SocioProphet/demo"
    )
    assert b["kind_class"] == "derived_content_drift"
    assert b["proposal"]["files"] == {"gen/registry.json": "NEW"}
    assert b["proposal"]["repo"] == "SocioProphet/demo"
    assert b["proposal"]["branch"].startswith("self-heal/derived_content_drift/")


def test_decide_governs_the_beacon_to_propose_pr():
    b = propose_derived_content_fix(
        path="gen/x.json", current="a", expected="b", repo="o/r"
    )
    receipt = decide(b, policy=POLICY)
    assert receipt["action"] == "propose_pr", receipt
    # not fenced off: boundary clean, IRI 0, evidence reproducible
    assert receipt["verdict"] != "BOTTOM"


def test_end_to_end_produce_decide_remediate_opens_pr(tmp_path):
    b = propose_derived_content_fix(
        path="gen/derived.json", current="stale", expected="fresh",
        repo="SocioProphet/demo",
    )
    receipt = decide(b, policy=POLICY)
    assert receipt["action"] == "propose_pr"

    seen = {}
    def fake_opener(proposal, *, repo_dir):
        seen["files"] = proposal["files"]
        seen["branch"] = proposal["branch"]
        return "https://example/pr/311"

    sealed = remediate(b, receipt, opener=fake_opener, repo_dir=tmp_path)
    assert sealed["converged"] is True                 # a reviewable PR now exists
    assert sealed["mode"] == "propose_pr"
    assert sealed["pr_url"] == "https://example/pr/311"
    assert sealed["trace_hash"]                          # sealed provenance
    # the PR carries exactly the regenerated bytes the producer computed
    assert seen["files"] == {"gen/derived.json": "fresh"}


def _run_all():
    import tempfile
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    for fn in fns:
        import inspect
        if "tmp_path" in inspect.signature(fn).parameters:
            with tempfile.TemporaryDirectory() as d:
                fn(Path(d))
        else:
            fn()
    print(f"beacon_producers (loop closed end-to-end): {len(fns)}/{len(fns)} tests pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(_run_all())


# ── deploy-regression → git-revert (the "still self-heals if it slips the canary" path) ──────
from automation.beacon_producers import propose_deploy_revert  # noqa: E402

DEPLOY_POLICY = dataclasses.replace(
    DEFAULT_POLICY,
    law_by_kind={**DEFAULT_POLICY.law_by_kind, "deploy_regression": "weak"},
)


def test_deploy_revert_beacon_carries_the_revert():
    b = propose_deploy_revert(repo="SocioProphet/prophet-platform", bad_commit="deadbeef1234",
                              app_name="search-api", reason="Degraded: 6/10 pods CrashLoopBackOff")
    assert b["kind_class"] == "deploy_regression"
    assert b["proposal"]["revert"] == "deadbeef1234"
    assert "files" not in b["proposal"]
    assert b["proposal"]["branch"].startswith("self-heal/deploy_regression/revert-")


def test_deploy_regression_end_to_end_opens_a_revert_pr(tmp_path):
    b = propose_deploy_revert(repo="SocioProphet/prophet-platform", bad_commit="deadbeef1234",
                              app_name="search-api", reason="sync failed")
    receipt = decide(b, policy=DEPLOY_POLICY)
    assert receipt["action"] == "propose_pr", receipt

    seen = {}
    def fake_opener(proposal, *, repo_dir):
        seen["revert"] = proposal.get("revert")
        return "https://example/pr/rollback-1"

    sealed = remediate(b, receipt, opener=fake_opener, repo_dir=tmp_path)
    assert sealed["converged"] is True and sealed["pr_url"] == "https://example/pr/rollback-1"
    assert seen["revert"] == "deadbeef1234"     # the loop reverts the offending commit
