name: build-sign-verify
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build here"
      - run: echo "Sign artifacts with cosign"
