"""Beacon producers — turn a detected failure SHAPE into a beacon the responder can act on.

The responder reasons and the self-heal loop actuates, but neither runs until something
produces a beacon. Detectors that can only observe emit warrantless/ proposal-less beacons
and the responder escalates. A *producer* goes further: for a shape whose corrective content
is locally computable, it attaches the concrete `proposal` (the fix, as files), so the loop
opens a reviewable fix PR instead of just paging a human.

`propose_derived_content_fix` is the first, and the most general honest one: a file that is
DERIVED from an in-repo source of truth has drifted from it. The corrected bytes are exactly
the regenerated content — fully local, fully deterministic — yet regeneration can be wrong in
ways only a human should wave through, so the class is governed to `propose_pr` (reviewed,
never silently auto-applied). This is the difference an owner feels vs. a closed OS/cloud:
the system notices its own drift and hands you the fix with its provenance, instead of
silently serving stale state.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Optional


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "fix"


def propose_derived_content_fix(
    *,
    path: str,
    current: str,
    expected: str,
    repo: str,
    kind_class: str = "derived_content_drift",
    branch: Optional[str] = None,
    title: Optional[str] = None,
    source_ref: Optional[str] = None,
    base: str = "main",
) -> Optional[dict]:
    """Beacon (with a concrete proposal) for a derived file that drifted from its source.

    Returns ``None`` when ``current == expected`` (in sync — nothing to heal), so callers can
    fan this over many derived files and only surface real drift. The beacon is shaped to pass
    the responder's fences: no boundary axis is breached (a same-repo regen), IRI stays 0
    (no identity entropy/injection), and the evidence is a reproducible detector reading — so
    ``meet(class-law, evidence)`` decides the action, and a class governed to ``weak`` yields
    ``propose_pr``: a reviewed fix PR carrying exactly the regenerated bytes.
    """
    if current == expected:
        return None

    rel = str(path)
    branch = branch or f"self-heal/{kind_class}/{_slug(rel)}"
    title = title or f"fix(self-heal): regenerate {rel} from its source of truth"
    ref = source_ref or f"file://{rel}"
    body = (
        f"`{rel}` has drifted from its source of truth and was regenerated.\n\n"
        f"- **source:** {ref}\n"
        f"- **why a PR (not an auto-fix):** regeneration is deterministic but reviewed, so a "
        f"human confirms the derived output before it lands.\n\n"
        f"Opened by the self-heal responder (class `{kind_class}`)."
    )
    return {
        "kind_class": kind_class,
        "system": f"{repo}:{rel}",
        "evidence": {"detector": "derived_content_drift", "reproducible": True, "stale": False},
        "evidence_ref": ref,
        "plan": {},  # same-repo derived-file regen — breaches no Ring-1 boundary axis
        "detail": {"path": rel, "reason": "derived file drifted from its source of truth"},
        "proposal": {
            "repo": repo,
            "base": base,
            "branch": branch,
            "title": title,
            "files": {rel: expected},
            "body": body,
        },
        "observed_at": _now(),
    }
