"""Beacon producers — turn a detected failure SHAPE into a beacon the responder can act on.

The responder reasons and the self-heal loop actuates, but neither runs until something
produces a beacon. Detectors that can only observe emit warrantless/ proposal-less beacons
and the responder escalates. A *producer* goes further: for a shape whose corrective content
is locally computable, it attaches the concrete `proposal` (the fix, as files), so the loop
opens a reviewable fix PR instead of just paging a human.

`propose_derived_content_fix` is the first, and the most general honest one: a file that is
DERIVED from an in-repo source of truth has drifted from it. The corrected bytes are exactly
the regenerated content — fully local, fully deterministic — yet regeneration can be wrong in
ways only a human should wave through, so the class is governed to `propose_pr` (reviewed,
never silently auto-applied). This is the difference an owner feels vs. a closed OS/cloud:
the system notices its own drift and hands you the fix with its provenance, instead of
silently serving stale state.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import List, Optional

from automation.macro_triad import TriadAssessment, assess_triad


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "fix"


def propose_derived_content_fix(
    *,
    path: str,
    current: str,
    expected: str,
    repo: str,
    kind_class: str = "derived_content_drift",
    branch: Optional[str] = None,
    title: Optional[str] = None,
    source_ref: Optional[str] = None,
    base: str = "main",
) -> Optional[dict]:
    """Beacon (with a concrete proposal) for a derived file that drifted from its source.

    Returns ``None`` when ``current == expected`` (in sync — nothing to heal), so callers can
    fan this over many derived files and only surface real drift. The beacon is shaped to pass
    the responder's fences: no boundary axis is breached (a same-repo regen), IRI stays 0
    (no identity entropy/injection), and the evidence is a reproducible detector reading — so
    ``meet(class-law, evidence)`` decides the action, and a class governed to ``weak`` yields
    ``propose_pr``: a reviewed fix PR carrying exactly the regenerated bytes.
    """
    if current == expected:
        return None

    rel = str(path)
    branch = branch or f"self-heal/{kind_class}/{_slug(rel)}"
    title = title or f"fix(self-heal): regenerate {rel} from its source of truth"
    ref = source_ref or f"file://{rel}"
    body = (
        f"`{rel}` has drifted from its source of truth and was regenerated.\n\n"
        f"- **source:** {ref}\n"
        f"- **why a PR (not an auto-fix):** regeneration is deterministic but reviewed, so a "
        f"human confirms the derived output before it lands.\n\n"
        f"Opened by the self-heal responder (class `{kind_class}`)."
    )
    return {
        "kind_class": kind_class,
        "system": f"{repo}:{rel}",
        "evidence": {"detector": "derived_content_drift", "reproducible": True, "stale": False},
        "evidence_ref": ref,
        "plan": {},  # same-repo derived-file regen — breaches no Ring-1 boundary axis
        "detail": {"path": rel, "reason": "derived file drifted from its source of truth"},
        "proposal": {
            "repo": repo,
            "base": base,
            "branch": branch,
            "title": title,
            "files": {rel: expected},
            "body": body,
        },
        "observed_at": _now(),
    }


def propose_deploy_revert(
    *,
    repo: str,
    bad_commit: str,
    app_name: str,
    reason: str,
    kind_class: str = "deploy_regression",
    branch: Optional[str] = None,
    base: str = "main",
) -> dict:
    """Beacon (with a REVERT proposal) for a deploy regression.

    An Argo app went unhealthy on a known git commit. The corrective action is a revert of that
    commit — and it must be a git revert, because Argo CD ``selfHeal: true`` re-applies git, so an
    in-cluster rollback gets undone; only reverting the offending commit sticks. This is the
    "if a bad merge slips the canary, it STILL self-heals" path: detect unhealthy -> this beacon
    -> reasoned responder -> a reviewed revert PR (governed to ``propose_pr``, never a silent
    force-push to prod). Shaped to pass the responder's fences (no boundary axis; IRI 0;
    reproducible detector), so ``meet(class-law, evidence)`` decides.
    """
    short = str(bad_commit)[:12]
    branch = branch or f"self-heal/{kind_class}/revert-{short}"
    title = f"revert(self-heal): {short} — {app_name} regressed in prod"
    body = (
        f"Argo app `{app_name}` went unhealthy on commit `{bad_commit}`.\n\n"
        f"- **reason:** {reason}\n"
        f"- **why a revert (not a patch):** Argo CD `selfHeal: true` re-applies git, so the only "
        f"rollback that sticks is reverting the offending commit.\n"
        f"- **why a PR (not auto-merge):** a production revert is reviewed.\n\n"
        f"Opened by the self-heal responder (class `{kind_class}`)."
    )
    return {
        "kind_class": kind_class,
        "system": f"{repo}@{short}",
        "evidence": {"detector": "deploy_health", "reproducible": True, "stale": False},
        "evidence_ref": f"argocd://app/{app_name}",
        "plan": {},  # reverting an in-repo commit breaches no Ring-1 boundary axis
        "detail": {"app": app_name, "bad_commit": bad_commit, "reason": reason},
        "proposal": {
            "repo": repo,
            "base": base,
            "branch": branch,
            "title": title,
            "revert": bad_commit,
            "body": body,
        },
        "observed_at": _now(),
    }


def propose_state_failback(
    receipts: list,
    *,
    repo: str,
    quorum: int = 2,
    kind_class: str = "deploy_regression",
    base: str = "main",
) -> List[dict]:
    """Beacons that fail a SICK k3s master-cluster back to the last state its peers still stand behind.

    This is the macro-triad closing the loop the design asked for: the three k3s masters each publish
    a Lazerus Integrity Receipt; :func:`automation.macro_triad.assess_triad` finds the canonical state
    a quorum agrees on (the last receipt-passing state) and names any master that diverged from it; and
    for each such master this producer emits a **failback** — a revert of the range from that canonical
    commit up to the commit the sick master is serving, so the cluster is amplified back to the
    quorum-blessed state. Reuses the #585 revert path (``proposal.revert``), because Argo CD
    ``selfHeal: true`` re-applies git and only a git revert sticks.

    Fail-closed and quorum-gated: returns ``[]`` unless a real 2-of-3 (``quorum``) healthy majority
    exists — with no trusted target, naming a "sick" cluster would be a guess, so nothing is proposed.
    A sick master with no divergent commit to revert (e.g. quarantined on the *same* commit — data
    corruption, not a bad deploy) yields no beacon here; that path is re-sync/quarantine, not revert.
    """
    assessment: TriadAssessment = assess_triad(receipts, quorum=quorum)
    if not assessment.needs_failback:
        return []  # no trusted majority, or a majority with nothing sick against it

    good_commit = assessment.canonical_commit
    beacons: List[dict] = []
    for sick in assessment.sick_clusters:
        head = sick.head_commit
        if not head or head == good_commit:
            # Nothing to revert TO a different commit — not a bad-deploy failback. Left for the
            # re-sync/quarantine path (a divergence in data, not in the deployed git state).
            continue
        # Fail back the range (good, head] — revert every commit the sick master took past the
        # last state the quorum signed. `git revert A..B` reverts each commit in reverse order.
        revert_range = f"{good_commit}..{head}"
        short_head = str(head)[:12]
        short_good = str(good_commit)[:12]
        cluster = sick.cluster
        branch = f"self-heal/{kind_class}/failback-{short_head}"
        title = f"revert(self-heal): fail {cluster} back to {short_good} (quorum-blessed state)"
        fence = f" Lazerus quarantine `{sick.koe_id}`." if sick.koe_id else ""
        body = (
            f"The k3s master triad diverged. A quorum of {len(assessment.healthy_clusters)} masters "
            f"agree on state `{assessment.canonical_state_root}` (commit `{good_commit}`); master "
            f"`{cluster}` diverged to commit `{head}`.{fence}\n\n"
            f"- **failback:** revert `{revert_range}` — amplify the sick cluster back to the last "
            f"state the master quorum stands behind.\n"
            f"- **why a revert (not a patch):** Argo CD `selfHeal: true` re-applies git, so only a "
            f"git revert of the divergent range sticks.\n"
            f"- **why a PR (not auto-merge):** a production failback is reviewed.\n"
            f"- **quorum:** {len(assessment.healthy_clusters)}/{len(receipts)} masters "
            f"(≥ {quorum}) — a trusted target exists, so this is a decision, not a guess.\n\n"
            f"Opened by the macro-triad self-heal responder (class `{kind_class}`)."
        )
        beacons.append({
            "kind_class": kind_class,
            "system": f"{repo}::{cluster}",
            "evidence": {"detector": "lazerus_macro_triad", "reproducible": True, "stale": False},
            "evidence_ref": sick.koe_id or f"lazerus://triad/{cluster}",
            "plan": {},  # reverting an in-repo commit range breaches no Ring-1 boundary axis
            "detail": {
                "cluster": cluster,
                "canonical_commit": good_commit,
                "sick_commit": head,
                "koe_id": sick.koe_id,
                "reason": sick.reason,
                "healthy_quorum": list(assessment.healthy_clusters),
            },
            "proposal": {
                "repo": repo,
                "base": base,
                "branch": branch,
                "title": title,
                "revert": revert_range,
                "body": body,
            },
            "observed_at": _now(),
        })
    return beacons
