#!/usr/bin/env python3
"""Lift the vendor-freshness register into the neurosymbolic repo graph (nrg:).

registry/vendor-freshness.yaml is the single source of truth for what is vendored,
and tools/validate_vendor_freshness.py::compute_state is the ONE definition of
"stale". This tool imports compute_state rather than reimplementing it, so the graph
can never hold a second opinion of freshness — it is a view, not a second register.

What the graph adds over the flat YAML is RELATIONAL reasoning the register cannot
express directly: a vendored artifact belongs to a source; a source has N consumers;
and a stale source's BLAST RADIUS is every consumer that vendors it. That is the same
neurosymbolic move the repo-graph reasoner already makes for spine/boundary/policy —
here applied to vendored-dependency health.

Output is deterministic — no clock, no host state — so `make validate` regenerates it
byte-for-byte and CI gates on a clean tree (same discipline as the SVF fixtures).

Usage:
  lift_vendor_freshness_to_graph.py            # print the graph to stdout
  lift_vendor_freshness_to_graph.py --write    # write it to the committed .ttl
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REGISTER = ROOT / "registry" / "vendor-freshness.yaml"
VALIDATOR = ROOT / "tools" / "validate_vendor_freshness.py"
OUTPUT = ROOT / "registry" / "neurosymbolic-repo-graph-reasoner" / "vendored-artifact.graph.ttl"

ARTIFACT_BASE = "https://socioprophet.org/ns/nrg/vendored-artifact/"
SOURCE_BASE = "https://socioprophet.org/ns/nrg/vendored-source/"


def _load_validator():
    spec = importlib.util.spec_from_file_location("validate_vendor_freshness", VALIDATOR)
    module = importlib.util.module_from_spec(spec)
    # Register before exec so the module's own dataclasses/annotations resolve.
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(spec.name, None)
        raise
    return module


def _lit(value: object) -> str:
    """A Turtle string literal with the handful of characters that must be escaped."""
    text = str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{text}"'


def _iri(base: str, tail: str) -> str:
    # artifact/source ids are ASCII [A-Za-z0-9@._-]; safe inside an IRI ref.
    return f"<{base}{tail}>"


def build() -> str:
    vf = _load_validator()
    data = yaml.safe_load(REGISTER.read_text(encoding="utf-8"))
    errors: list[str] = []
    sources, artifacts = vf.check_shape(data, errors)
    if errors:
        raise SystemExit("ERR: vendor-freshness register fails shape checks: " + "; ".join(errors))

    # Relational rollup: which consumers each source feeds, and which are stale.
    consumers: dict[str, list[str]] = {}
    stale_consumers: dict[str, list[str]] = {}
    computed: dict[str, tuple[str, str]] = {}
    for art in artifacts:
        sid = art["source_id"]
        state, reason = vf.compute_state(art, sources[sid])
        computed[art["artifact_id"]] = (state, reason)
        consumers.setdefault(sid, []).append(art["artifact_id"])
        if state == "stale":
            stale_consumers.setdefault(sid, []).append(art["artifact_id"])

    out: list[str] = [
        "@prefix nrg: <https://socioprophet.org/ns/neurosymbolic-repo-graph#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        "# GENERATED by tools/lift_vendor_freshness_to_graph.py from registry/vendor-freshness.yaml.",
        "# Freshness is imported from validate_vendor_freshness.compute_state (the one definition",
        "# of stale). Do not hand-edit; run `make neurosymbolic-vendored-artifact-graph-write`.",
        "",
    ]

    for art in artifacts:
        sid = art["source_id"]
        source = sources[sid]
        state, reason = computed[art["artifact_id"]]
        node = _iri(ARTIFACT_BASE, art["artifact_id"])
        triples = [
            f"{node}",
            "  a nrg:VendoredArtifact ;",
            f"  nrg:artifactId {_lit(art['artifact_id'])} ;",
            f"  nrg:sourceId {_lit(sid)} ;",
            f"  nrg:vendoredFrom {_iri(SOURCE_BASE, sid)} ;",
            f"  nrg:consumerRepo {_lit(art['consumer_repo'])} ;",
            f"  nrg:consumerApp {_lit(art['consumer_app'])} ;",
            f"  nrg:freshnessPolicy {_lit(art['freshness_policy'])} ;",
            f"  nrg:freshnessState {_lit(state)} ;",
            f"  nrg:freshnessReason {_lit(reason)} ;",
            f"  nrg:disposition {_lit(art.get('disposition', ''))} ",
        ]
        for key, prop in (
            ("vendored_version", "nrg:vendoredVersion"),
            ("vendored_digest", "nrg:vendoredDigest"),
        ):
            if art.get(key):
                triples[-1] = triples[-1].rstrip() + " ;"
                triples.append(f"  {prop} {_lit(art[key])} ")
        if source.get("upstream_latest_version"):
            triples[-1] = triples[-1].rstrip() + " ;"
            triples.append(f"  nrg:upstreamLatestVersion {_lit(source['upstream_latest_version'])} ")
        triples[-1] = triples[-1].rstrip() + " ."
        out.extend(triples)
        out.append("")

    # Source nodes carry the blast-radius rollup — the reasoning the flat register cannot state.
    for sid in sorted(consumers):
        fed = consumers[sid]
        stale = stale_consumers.get(sid, [])
        node = _iri(SOURCE_BASE, sid)
        radius = ", ".join(sorted(stale)) if stale else "none"
        out.extend([
            f"{node}",
            "  a nrg:VendoredSource ;",
            f"  nrg:sourceId {_lit(sid)} ;",
            f"  nrg:consumerCount {len(fed)} ;",
            f"  nrg:staleConsumerCount {len(stale)} ;",
            f"  nrg:blastRadius {_lit(radius)} ;",
            "  nrg:chronosReasoning "
            + _lit(
                f"a stale source propagates to every consumer that vendors it; "
                f"{sid} staleness has blast radius {{{radius}}}"
            )
            + " .",
            "",
        ])

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    graph = build()
    if "--write" in sys.argv[1:]:
        OUTPUT.write_text(graph, encoding="utf-8")
        print(f"OK: wrote {OUTPUT.relative_to(ROOT)}")
    else:
        sys.stdout.write(graph)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
